version: '3.9'
services:
    mariadb:
        image: mariadb:10.3
        container_name: mariadb
        environment:
            MYSQL_ROOT_PASSWORD: HealthX!Chain123Root
            MYSQL_DATABASE: swabx
            MYSQL_USER: swabx
            MYSQL_PASSWORD: HealthX!Chain123BLR
        networks:
            - vpcbr
        healthcheck:
            test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
            timeout: 20s
            retries: 30

    redis:
        image: bitnami/redis:latest
        container_name: redis
        environment:
            REDIS_PASSWORD: HealthX!Chain123BLR
        networks:
            - vpcbr

    mongo:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: HealthX!Chain123Root
        networks:
            - vpcbr

    appointment:
        image: blockchain.azurecr.io/appointment_scheduler
        container_name: appointment
        environment:
            NODE_ENV: production
            loglevel: all
            MYSQL_DIALECT: mariadb
            MYSQL_HOST: mariadb
            MYSQL_PORT: 3306
            MYSQL_DATABASE: swabx
            MYSQL_USER: swabx
            MYSQL_PASSWORD: HealthX!Chain123BLR
        networks:
            - vpcbr
        
    api:
        image: blockchain.azurecr.io/breathalyzer_api:swabx
        container_name: api
        ports: 
            - "443:443"
        networks:
            - vpcbr
        links:
            - mariadb
        depends_on:
            mariadb:
                condition: service_healthy
        environment:
            CLIENT_NAME: SwabX
            NODE_ENV: production
            MYSQL_HOST: mariadb
            MYSQL_PORT: 3306
            MYSQL_DATABASE: swabx
            MYSQL_USER: swabx
            MYSQL_PASSWORD: HealthX!Chain123BLR
            SECRET: 551531dca26542b188cb3803ab4de7b9
            AS_URL: http://appointment:8985/api/v1.0.0
            BC_URL: http://10.2.0.4:8080/api/v1
            MONGO_URL: mongodb://localhost:2222
            MONGO_DATABASE: HealthX_1
            PUBLIC_URL: https://swabx.healthx.global
            OTP_EXPIRY_TIME: 5m
            REFRESH_TOKEN_EXPIRY: 7d
            JWT_TOKEN_EXPIRY: 1h
            REDIS_HOST: redis
            REDIS_PORT: 6379
            REDIS_PASSWORD: HealthX!Chain123BLR
        restart: always
    
networks:
    vpcbr:
        driver: bridge
